### PR TITLE
python3 update, and bump requirement versions

### PR DESCRIPTION
**Pull request by orangepeelbeef**
Updated requirements files to more modern versions
updated write file to be binary for python3

### CODE REVIEW

**Comment by inhumantsar** [comment]
sorry, this fell through the cracks. just seeing it now. 

could you do a couple more things before this gets accepted though?

* remove the commented out lines/files. if we ever need to go back and re-enable them, we can use git history to do it.
* add a github actions workflow to run unit tests

also, i noticed that you've removed the tests for inline secrets. why is that?

**Comment by orangepeelbeef** [comment]
Ah i forgot this pr was still open.  Initially I just fixed the code so it
worked.  Problem is it expected everything to be yaml files.  But our
company doesn't use the inline secrets and it was easier for my purposes to
just rip out comment out those bits. We have some fully encrypted files
that are not yaml at all (which is perfectly fine except this script puked
on those files)
Ansibleloader automatically decrypts the inline secrets but I didn't find a
way to tell from the object that it did have secrets in it.  Which means
that I can't re encrypt the inline secrets as is.

Ultimately it would be nice to get that functionality back in and working
but the code I have checked in and using in my branch is only working with
fully encrypted files.

I had major issues with whitespace and etc changing with how the code was
originally set up.  (Forcing everything through yaml parser destroyed all
the whitespace).

This code preserves the original file and just re encrypts it.

I will see if I can get the yaml secrets function working again.  If not I
may just have to keep this as separate project.

**Comment by mbassett** [comment]
Ok, inline secret functionality should be restored.  All tests are passing except it doesn't like that i have 2 functions declared imported that are not used yet.  I left them there because they should be used and i didn't want to have to go dig out the function names.

is_encrypted_file should replace the  is_file_secret def and 
get_file_vault_secret  should be used wherever the password file is being loaded

**Comment by orangepeelbeef** [comment]
Ok, inline secret functionality should be restored.

All tests are passing in tox except the 2 imports that are not used currently

get_vault_secret should be used wherever we are directly loading password files with opens

is_encrypted_file  should replace the  is_file_secret def

I left them in because I didn't want to have to go digging up the names, but I haven't swapped the code yet.

**Comment by orangepeelbeef** [comment]
gh-actions is failing due to the aforementioned unused imports.
<pre>
flake8 run-test: commands[0] | flake8 --ignore=E501 ansible_vault_rekey
ansible_vault_rekey/ansible_vault_rekey.py:17:1: F401 'ansible.parsing.vault.get_file_vault_secret' imported but unused
ansible_vault_rekey/ansible_vault_rekey.py:17:1: F401 'ansible.parsing.vault.is_encrypted_file' imported but unused
ERROR: InvocationError for command /home/runner/work/python-ansible-vault-rekey/python-ansible-vault-rekey/.tox/flake8/bin/flake8 --ignore=E501 ansible_vault_rekey (exited with code 1)
<pre>

**Comment by rkokkelk** [comment]
Thank you for your contribution. I've recently joined as collaborator and I'm looking at your content. However, it is a bit much to directly merge it into master. I've just joined it with develop and make it production ready as soon as possible.

Because of merge in develop this PR will be closed. Thanks!

**Pull request closed without merging**
